name: Deploy Apps

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      node_changed: ${{ steps.filter.outputs.node }}
      java_changed: ${{ steps.filter.outputs.java }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            node:
              - 'node/**'
            java:
              - 'java/**'
 
 

  deploy-node:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build and run Node app
        run: |
          cd node
          docker build -t node-image .
          docker stop node-image
	  docker ps
          docker rm node-image || true
          docker run -d --name node-app --network hw node-app

      - name: Verify Node deployment
        run: |
          sleep 10
          curl http://localhost:3000

  deploy-java:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build and run Spring Boot app
        run: |
          cd java
          docker build -t java-image .
          docker stop java-image || true
          docker rm java-image || true
          docker run -d --name java-app --network hw java-image

      - name: Verify Java deployment
        run: |
          sleep 10
          curl http://localhost:8080
