name: Deploy Apps
on:
  push:
    branches:
      - main

jobs:
  sast-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-node:
    needs: sast-scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Build and run Node app
        run: |
          cd node
          docker build -t node-image .
          docker stop node-app || true
          docker rm node-app || true
          docker run -d --name node-app --network hw node-image
      - run: sleep 10 && curl http://localhost:3000

  deploy-java:
    needs: sast-scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Build and run Spring Boot app
        run: |
          cd java
          docker build -t java-image .
          docker stop java-app || true
          docker rm java-app || true
          docker run -d --name java-app --network hw java-image
      - run: sleep 10 && curl http://localhost:8080

  deploy-reverse-proxy:
    needs: [deploy-node, deploy-java]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Build and deploy reverse proxy
        run: |
          cd reverse-proxy
          docker build -t proxy-image .
          docker stop lab || true
          docker rm lab || true
          docker run -d --name lab --network hw -p 8080:80 proxy-image
      - name: Verify communication
        run: |
          docker exec java-app ping -c 4 node-app
          docker exec java-app ping -c 4 lab